//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.aerilys.geowarfare.android.activities;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.aerilys.geowarfare.android.R.id;
import com.aerilys.geowarfare.android.R.layout;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class ResultBattleActivity_
    extends ResultBattleActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_result_battle);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        resultBattleSectorName = ((TextView) findViewById(id.resultBattleSectorName));
        lossBattleLabel = ((TextView) findViewById(id.lossBattleLabel));
        resultBattleLabel = ((TextView) findViewById(id.resultBattleLabel));
        bindDatas();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static ResultBattleActivity_.IntentBuilder_ intent(Context context) {
        return new ResultBattleActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ResultBattleActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ResultBattleActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

    }

}
